package com.humility.client.view;

import com.formdev.flatlaf.FlatLightLaf;
import com.humility.client.view.component.ChatRoom;
import com.humility.client.view.component.Home;
import com.humility.client.view.component.Sell;

/**
 * @author Humility <Yiling Yu>
 */

public class Main extends javax.swing.JFrame {

  /**
   * Creates new form Home
   */
  public Main() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    sell_label = new javax.swing.JLabel();
    layout_panel = new javax.swing.JLayeredPane();
    home_label = new javax.swing.JLabel();
    chat_label = new javax.swing.JLabel();
    home = new Home();
    chatRoom = new ChatRoom();
    sell = new Sell();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBounds(220, 12, 1024, 768);
    setTitle("二手交易市场");

    sell_label.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
    sell_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    sell_label.setText("Sell");
    sell_label.setPreferredSize(new java.awt.Dimension(64, 252));
    sell_label.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        sell_labelMouseClicked(evt);
      }
    });

    layout_panel.setPreferredSize(new java.awt.Dimension(956, 768));

    javax.swing.GroupLayout layout_panelLayout = new javax.swing.GroupLayout(layout_panel);
    layout_panel.setLayout(layout_panelLayout);
    layout_panelLayout.setHorizontalGroup(
            layout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 956, Short.MAX_VALUE)
    );
    layout_panelLayout.setVerticalGroup(
            layout_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 0, Short.MAX_VALUE)
    );
    layout_panel.add(home, 0);
    layout_panel.add(chatRoom, 1);
    layout_panel.add(sell, -1);

    home_label.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
    home_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    home_label.setText("Home");
    home_label.setPreferredSize(new java.awt.Dimension(64, 252));
    home_label.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        home_labelMouseClicked(evt);
      }
    });

    chat_label.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
    chat_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    chat_label.setText("Chat");
    chat_label.setPreferredSize(new java.awt.Dimension(64, 252));
    chat_label.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        chat_labelMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sell_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(home_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chat_label, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(layout_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(layout_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(home_label, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(chat_label, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(sell_label, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(34, 34, 34))
    );

    pack();
  }// </editor-fold>

  private void home_labelMouseClicked(java.awt.event.MouseEvent evt) {
    home.setVisible(true);
    chatRoom.setVisible(false);
    sell.setVisible(false);
  }

  private void chat_labelMouseClicked(java.awt.event.MouseEvent evt) {
    chatRoom.setVisible(true);
    sell.setVisible(false);
    home.setVisible(false);
  }

  private void sell_labelMouseClicked(java.awt.event.MouseEvent evt) {
    sell.setVisible(true);
    chatRoom.setVisible(false);
    home.setVisible(false);
  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the look and feel */
    try {
      javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Main().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify
  private javax.swing.JLabel chat_label;
  private javax.swing.JLabel home_label;
  private javax.swing.JLayeredPane layout_panel;
  private javax.swing.JLabel sell_label;
  private Home home;
  private ChatRoom chatRoom;
  private Sell sell;
  // End of variables declaration
}
