package com.humility.client.view;

import com.formdev.flatlaf.FlatLightLaf;
import com.humility.client.Client;
import com.humility.datas.User;

import javax.swing.*;

/**
 * @author Humility <Yiling Yu>
 */

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        register_font = new javax.swing.JLabel();
        separator_top = new javax.swing.JSeparator();
        app_intro = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        realname_label = new javax.swing.JLabel();
        phone_number_label = new javax.swing.JLabel();
        qq_account_label = new javax.swing.JLabel();
        email_address_label = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        realname = new javax.swing.JTextField();
        phone_number = new javax.swing.JTextField();
        qq_account = new javax.swing.JTextField();
        email_address = new javax.swing.JTextField();
        separator_buttom = new javax.swing.JSeparator();
        author = new javax.swing.JLabel();
        hand_in = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("二手交易市场");

        register_font.setFont(new java.awt.Font("宋体", 1, 48)); // NOI18N
        register_font.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        register_font.setText("注册");
        register_font.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        app_intro.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        app_intro.setText("java课程设计:二手交易平台");

        username_label.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        username_label.setText("用 户 名:");
        username_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        username.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        password_label.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        password_label.setText("密    码:");
        password_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        realname_label.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        realname_label.setText("真实姓名:");
        realname_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        phone_number_label.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        phone_number_label.setText("电话号码:");
        phone_number_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        qq_account_label.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        qq_account_label.setText("Q Q 账号:");
        qq_account_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        email_address_label.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
        email_address_label.setText("邮箱地址:");
        email_address_label.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        password.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        realname.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        realname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realnameActionPerformed(evt);
            }
        });

        phone_number.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        phone_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_numberActionPerformed(evt);
            }
        });

        qq_account.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        qq_account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qq_accountActionPerformed(evt);
            }
        });

        email_address.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        email_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_addressActionPerformed(evt);
            }
        });

        author.setFont(new java.awt.Font("微软雅黑 Light", 0, 12)); // NOI18N
        author.setText("Author: Humility_YilingYu");

        hand_in.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
        hand_in.setText("提      交");
        hand_in.setActionCommand("提               交");
        hand_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hand_inActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(separator_top, javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(70, 70, 70)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(email_address, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(qq_account, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(phone_number, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(realname, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(password_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(realname_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(qq_account_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(email_address_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(phone_number_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(username_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(hand_in, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(71, 71, 71))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(app_intro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(register_font, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(275, 275, 275)
                                                .addComponent(author))
                                        .addComponent(separator_buttom, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(register_font, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(app_intro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(separator_top, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(username_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(password_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(realname_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(realname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(phone_number_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qq_account_label, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(qq_account, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(email_address_label, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(email_address, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hand_in, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(separator_buttom, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void realnameActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void phone_numberActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void qq_accountActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void email_addressActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void hand_inActionPerformed(java.awt.event.ActionEvent evt) {
        User user = new User();
        user.setUser_id(0);
        if (!username.getText().trim().equals("") && !password.getText().trim().equals("")) {
            user.setUsername(username.getText());
            user.setPassword(password.getText().hashCode());
            user.setRealname(realname.getText());
            user.setPhoneNumber(phone_number.getText());
            user.setEmailAddress(email_address.getText());
            user.setQqAccount(qq_account.getText());
            //TODO 在前台检验信息是否合法
            Boolean flag = false;
            flag = Client.getClient().getUserService().register(user);
            if (flag) {
                JOptionPane.showMessageDialog(this, "注册成功!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "注册失败, 请检查信息是否违法以及网络连接.");
            }

        } else {
            JOptionPane.showMessageDialog(this, "用户名和密码不能为空!");
        }
        return;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //set flatlightlaf look and feel.
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        //创建并绘制register的实例.
        java.awt.EventQueue.invokeLater(() -> {
            Register register = new Register();
            register.setLocationRelativeTo(null);
            register.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
            register.setVisible(true);
        });
    }

    //register私有属性.
    private javax.swing.JLabel app_intro;
    private javax.swing.JLabel author;
    private javax.swing.JTextField email_address;
    private javax.swing.JLabel email_address_label;
    private javax.swing.JButton hand_in;
    private javax.swing.JTextField password;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField phone_number;
    private javax.swing.JLabel phone_number_label;
    private javax.swing.JTextField qq_account;
    private javax.swing.JLabel qq_account_label;
    private javax.swing.JTextField realname;
    private javax.swing.JLabel realname_label;
    private javax.swing.JLabel register_font;
    private javax.swing.JSeparator separator_buttom;
    private javax.swing.JSeparator separator_top;
    private javax.swing.JTextField username;
    private javax.swing.JLabel username_label;
}

