package com.humility.client.view.component;

/**
 * @author Humility <Yiling Yu>
 */

public class ChatRoom extends javax.swing.JPanel {

  /**
   * Creates new form ChatRoom
   */
  public ChatRoom() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {

    jSeparator1 = new javax.swing.JSeparator();
    deal = new javax.swing.JButton();
    message_board = new javax.swing.JScrollPane();
    jScrollPane2 = new javax.swing.JScrollPane();
    message_input = new javax.swing.JTextArea();
    communications = new javax.swing.JScrollPane();
    send = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(956, 768));
    setBounds(0, 0, 956, 768);
    setOpaque(true);


    deal.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
    deal.setText("成  交");
    deal.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dealActionPerformed(evt);
      }
    });

    message_input.setColumns(20);
    message_input.setRows(5);
    message_input.addKeyListener(new java.awt.event.KeyAdapter() {
      public void keyReleased(java.awt.event.KeyEvent evt) {
        message_inputKeyReleased(evt);
      }
    });
    jScrollPane2.setViewportView(message_input);

    communications.setPreferredSize(new java.awt.Dimension(264, 768));

    send.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
    send.setText("发  送");
    send.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sendActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addComponent(communications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(message_board, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(deal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(29, 29, 29)
                                            .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(232, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jSeparator1)
                            .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                            .addComponent(communications, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(message_board, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(deal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(77, 77, 77))
    );

  }

  private void message_inputKeyReleased(java.awt.event.KeyEvent evt) {
    // TODO 回车发送信息.
  }

  private void sendActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO 发送信息
  }

  private void dealActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO 创建交易
  }

  // Variables declaration - do not modify
  private javax.swing.JScrollPane communications;
  private javax.swing.JButton deal;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JScrollPane message_board;
  private javax.swing.JTextArea message_input;
  private javax.swing.JButton send;
  // End of variables declaration
}
