package com.humility.client.view.component;

/**
 * @author Humility <Yiling Yu>
 */

public class Good extends javax.swing.JPanel {

  /**
   * Creates new form Good
   */
  public Good() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    jLabel2 = new javax.swing.JLabel();
    picture = new javax.swing.JLabel();
    name = new javax.swing.JLabel();
    price = new javax.swing.JLabel();
    description = new javax.swing.JLabel();
    i_wanna = new javax.swing.JButton();

    jLabel2.setText("jLabel2");

    setMaximumSize(new java.awt.Dimension(183, 230));
    setMinimumSize(new java.awt.Dimension(183, 230));
    setName(""); // NOI18N
    setPreferredSize(new java.awt.Dimension(183, 230));

    picture.setPreferredSize(new java.awt.Dimension(183, 100));

    name.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
    name.setText("name");

    price.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
    price.setText("price");

    description.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
    description.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
    description.setText("jLabel7");
    description.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    i_wanna.setText("i_wanna");
    i_wanna.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        i_wannaActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(i_wanna, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(picture, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(i_wanna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
    );
  }// </editor-fold>

  private void i_wannaActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }


  // Variables declaration - do not modify
  private javax.swing.JLabel description;
  private javax.swing.JButton i_wanna;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel name;
  private javax.swing.JLabel picture;
  private javax.swing.JLabel price;
  // End of variables declaration
}

