package com.humility.client.view.component;

import com.humility.client.Client;
import com.humility.datas.Good;

import javax.swing.*;
import java.util.List;

/**
 * @author Humility <Yiling Yu>
 */
public class Home extends javax.swing.JPanel {

  /**
   * Creates new form Home
   */
  public Home() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {

    search_icon = new javax.swing.JLabel();
    post = new javax.swing.JLabel();
    good_scroll = new javax.swing.JScrollPane();
    good_panel = new java.awt.Panel();
    search_box = new javax.swing.JTextField();

    getGoodsView();

    setPreferredSize(new java.awt.Dimension(956, 768));
    setBounds(0, 0, 956, 768);


    javax.swing.GroupLayout good_panelLayout = new javax.swing.GroupLayout(good_panel);
    good_panel.setLayout(good_panelLayout);
    good_panelLayout.setHorizontalGroup(
            good_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 742, Short.MAX_VALUE)
    );
    good_panelLayout.setVerticalGroup(
            good_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGap(0, 228, Short.MAX_VALUE)
    );


    good_scroll.setViewportView(good_panel);

    post.setIcon(new ImageIcon("E:\\java\\curriculum-design\\client\\src\\main\\resources\\ps5_c.jpg"));

    search_icon.setIcon(new ImageIcon("E:\\java\\curriculum-design\\client\\src\\main\\resources\\search.png"));
    search_icon.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        search_iconMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap(113, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(search_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(search_box))
                                    .addComponent(post, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(good_scroll, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(87, 87, 87))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(search_icon, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                    .addComponent(search_box))
                            .addGap(26, 26, 26)
                            .addComponent(post, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                            .addGap(38, 38, 38)
                            .addComponent(good_scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(24, 24, 24))
    );
  }

  public void getGoodsView() {
    good_panel.removeAll();
    goodList = Client.getClient().getGoodService().getGoodsList();
    com.humility.client.view.component.Good good_c = null;
    for (int i = 0; i < goodList.size(); i++) {
      good_c = new com.humility.client.view.component.Good(goodList.get(i));
      good_c.setBounds((i%4)*183 + 2*i, i/4*230, 183, 230);
      good_panel.add(good_c);
    }
    good_panel.repaint();
  }

  private void search_iconMouseClicked(java.awt.event.MouseEvent evt) {
    // TODO add your handling code here:
  }

  // Variables declaration - do not modify
  private javax.swing.JLabel post;
  private javax.swing.JTextField search_box;
  private javax.swing.JLabel search_icon;
  private java.awt.Panel good_panel;
  private javax.swing.JScrollPane good_scroll;
  private List<Good> goodList;
  // End of variables declaration
}

