package com.humility.client.view.component;

import com.formdev.flatlaf.FlatLightLaf;
import com.humility.client.Client;
import com.humility.client.view.Login;
import com.humility.client.view.Main;
import com.humility.datas.Good;

import javax.swing.*;
import java.awt.*;
import java.math.BigDecimal;

/**
 * @author Humility <Yiling Yu>
 */

public class ReleaseGood extends javax.swing.JDialog {

  /**
   * Creates new form ReleaseGood
   */
  public ReleaseGood(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {

    title_label = new javax.swing.JLabel();
    gprice_label = new javax.swing.JLabel();
    gname = new javax.swing.JTextField();
    gname_label = new javax.swing.JLabel();
    price = new javax.swing.JTextField();
    description_label = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    description = new javax.swing.JTextArea();
    picture_label = new javax.swing.JLabel();
    sp_bt = new javax.swing.JButton();
    confirm_bt = new javax.swing.JButton();

    setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    setLocation(500, 200);

    title_label.setFont(new java.awt.Font("幼圆", 1, 24)); // NOI18N
    title_label.setText(" 发布商品");

    gprice_label.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
    gprice_label.setText("商品价格");

    gname.setPreferredSize(new java.awt.Dimension(175, 29));

    gname_label.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
    gname_label.setText("商品名称");

    price.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        priceActionPerformed(evt);
      }
    });

    description_label.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
    description_label.setText("商品描述");

    description.setColumns(20);
    description.setRows(5);
    description.setLineWrap(true);
    jScrollPane1.setViewportView(description);

    picture_label.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
    picture_label.setText("商品图片");

    sp_bt.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
    sp_bt.setText("选 择 本 地 图 片");
    sp_bt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        sp_btActionPerformed(evt);
      }
    });

    confirm_bt.setFont(new java.awt.Font("幼圆", 0, 24)); // NOI18N
    confirm_bt.setText("确 认 发 布");
    confirm_bt.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        confirm_btActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(confirm_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                    .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGroup(layout.createSequentialGroup()
                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                    .addComponent(gprice_label)
                                                                                    .addComponent(gname_label)
                                                                                    .addComponent(description_label))
                                                                            .addGap(10, 10, 10)))
                                                            .addGap(18, 18, 18))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addGap(52, 52, 52)
                                                            .addComponent(picture_label)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(price)
                                                    .addComponent(gname, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                                    .addComponent(jScrollPane1)
                                                    .addComponent(sp_bt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addContainerGap(71, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(title_label, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(gname_label)
                                            .addGap(35, 35, 35)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(gprice_label)))
                                    .addComponent(gname, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(description_label)
                                            .addGap(132, 132, 132)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(sp_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(picture_label)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(confirm_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(34, Short.MAX_VALUE))
    );

    pack();
  }

  private void sp_btActionPerformed(java.awt.event.ActionEvent evt) {
    createFileChooser();
  }

  private void priceActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO add your handling code here:
  }

  private void confirm_btActionPerformed(java.awt.event.ActionEvent evt) {
    createGood();
    Boolean flag = Client.getClient().getGoodService().releaseGood(good);
    if (flag == null)
      JOptionPane.showMessageDialog(this, "服务请求失败,请检查网络连接.");
    if (flag) {
      JOptionPane.showMessageDialog(this, "商品发布成功!");
      this.dispose();
      Main.home.getGoodsView();
    }
    else {
      JOptionPane.showMessageDialog(this, "商品发布失败, 请完善商品信息。");
    }

  }

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the look and feel */
    try {
      javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        ReleaseGood dialog = new ReleaseGood(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }

  /**
   * 创建文件选择窗口,以选择商品图像.
   */
  private void createFileChooser() {
    fc = new JFileChooser();
    fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
    fc.showOpenDialog(getParent());
  }

  private void createGood() {
    good = new Good();
    good.setGname(gname.getText());
    good.setOwner(Client.getClient().getMe());
    good.setDescription(description.getText());
    good.setIs_selled(false);
    good.setPrice(new BigDecimal(price.getText()));
    picture = new ImageIcon(fc.getSelectedFile().getAbsolutePath());
    Image img = picture.getImage().getScaledInstance(183, 100, Image.SCALE_DEFAULT);
    good.setImage(new ImageIcon(img));
  }
  // Variables declaration - do not modify
  private javax.swing.JButton confirm_bt;
  private javax.swing.JTextArea description;
  private javax.swing.JLabel description_label;
  private javax.swing.JTextField gname;
  private javax.swing.JLabel gname_label;
  private javax.swing.JLabel gprice_label;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JLabel picture_label;
  private javax.swing.JTextField price;
  private javax.swing.JButton sp_bt;
  private javax.swing.JLabel title_label;
  private JFileChooser fc;
  private ImageIcon picture;
  private Good good;
  // End of variables declaration
}
