package com.humility.client.view.component;

/**
 * @author Humility <Yiling Yu>
 */
public class Sell extends javax.swing.JPanel {

  /**
   * Creates new form Sell
   */
  public Sell() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">
  private void initComponents() {

    statistic = new javax.swing.JButton();
    release = new javax.swing.JButton();
    selled_goods = new javax.swing.JScrollPane();
    aution = new javax.swing.JButton();
    label = new javax.swing.JLabel();

    setPreferredSize(new java.awt.Dimension(956, 768));
    setBounds(0, 0, 956, 768);
    setOpaque(true);

    statistic.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
    statistic.setText("销售数据统计");
    statistic.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        statisticActionPerformed(evt);
      }
    });

    release.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
    release.setText("发 布 商 品");
    release.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        releaseActionPerformed(evt);
      }
    });

    aution.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
    aution.setText("发 起 拍 卖");
    aution.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        autionActionPerformed(evt);
      }
    });

    label.setFont(new java.awt.Font("幼圆", 1, 18)); // NOI18N
    label.setText("已售商品");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(selled_goods, javax.swing.GroupLayout.PREFERRED_SIZE, 789, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                            .addComponent(release, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(172, 172, 172)
                                            .addComponent(aution, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(122, 122, 122)
                                            .addComponent(statistic, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap(127, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(selled_goods, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(release, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(aution, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statistic, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33))
    );

  }// </editor-fold>

  private void autionActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO 发起拍卖.
  }

  private void statisticActionPerformed(java.awt.event.ActionEvent evt) {
    // TODO 统计销售数据(按时段).
  }

  private void releaseActionPerformed(java.awt.event.ActionEvent evt) {
    ReleaseGood.main(null);
  }

  // Variables declaration - do not modify
  private javax.swing.JButton aution;
  private javax.swing.JLabel label;
  private javax.swing.JButton release;
  private javax.swing.JScrollPane selled_goods;
  private javax.swing.JButton statistic;
  // End of variables declaration
}
