package com.humility.client.view.component;

import com.humility.client.Client;
import com.humility.datas.Good;
import com.humility.datas.Message;

import javax.swing.*;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Humility <Yiling Yu>
 */
public class Session extends javax.swing.JPanel {

  /**
   * Creates new form Communication
   */
  public Session(com.humility.datas.Good good, int buyer_id) {
    messages = new ArrayList<>();
    this.good = good;
    this.buyer_id = buyer_id;
    initComponents();
    panel = new JPanel();
    ChatRoom.show_panel.add(panel);
    panel.setBounds(0, 0, 612, 540);
    ChatRoom.show_panel.setLayer(panel, 0, ChatRoom.sessions.size());
    panel.setVisible(true);
    ChatRoom.getFocus(this);
  }

  public  void refreshPanel() {
    panel.removeAll();
    int i = 0;
    for (Message message: messages) {
      com.humility.client.view.component.Message msg = new com.humility.client.view.component.Message(message);
      panel.add(msg);
      msg.setBounds(0, i * 98, 612, 96);
      msg.setVisible(true);
      i++;
    }
    panel.setVisible(true);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  private void initComponents() {

    close_button = new javax.swing.JLabel();
    username = new javax.swing.JLabel();
    goodname = new javax.swing.JLabel();

    setMaximumSize(new java.awt.Dimension(264, 64));
    setMinimumSize(new java.awt.Dimension(264, 64));
    setPreferredSize(new java.awt.Dimension(264, 64));
    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        formMouseClicked(evt);
      }
    });

    close_button.setPreferredSize(new java.awt.Dimension(45, 45));
    close_button.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        close_buttonMouseClicked(evt);
      }
    });

    username.setFont(new java.awt.Font("幼圆", 0, 18)); // NOI18N
    username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    username.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    if (Client.getClient().getMe() == buyer_id) {
      other_id = good.getOwner();
      username.setText(Client.getClient().getUserService().getUserByUid(other_id).getUsername());
    }
    else {
      other_id = buyer_id;
      username.setText(Client.getClient().getUserService().getUserByUid(other_id).getUsername());
    }

    goodname.setFont(new java.awt.Font("幼圆", 0, 14)); // NOI18N
    goodname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    goodname.setText(good.getGname());

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(goodname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(57, 57, 57)
                            .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
    );
    layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(goodname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(close_button, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }

  private void close_buttonMouseClicked(java.awt.event.MouseEvent evt) {
    ChatRoom.sessions.remove(this);
    this.panel.removeAll();
    this.panel.setVisible(false);
    ChatRoom.paintSessionPanel();
  }

  private void formMouseClicked(java.awt.event.MouseEvent evt) {
    ChatRoom.getFocus(this);
    refreshPanel();
  }

  // Variables declaration - do not modify
  private javax.swing.JLabel goodname;
  private javax.swing.JLabel close_button;
  private javax.swing.JLabel username;

  public Good getGood() {
    return good;
  }

  public int getBuyer_id() {
    return buyer_id;
  }

  public Good good;
  private int buyer_id;
  public int other_id;
  public JPanel panel;
  public List<Message> messages;
  // End of variables declaration
}

